-- MySQL Script generated by MySQL Workbench
-- Mon Nov  3 18:40:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prescription` (
  `id` BIGINT NOT NULL,
  `treatment_id` BIGINT NULL,
  `medication` VARCHAR(45) NULL,
  `dosage_mg` INT NULL,
  `frequency` VARCHAR(45) NULL,
  `duration_days` INT NULL,
  `instructions` TEXT NULL,
  `prescribed_date` DATE NULL DEFAULT CURRENT_DATE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treatment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT NOT NULL,
  `doctor_id` BIGINT NULL,
  `admission_id` BIGINT NULL,
  `diagnosis` VARCHAR(45) NOT NULL,
  `treatment_start_date` DATE NULL,
  `treatment_end_date` DATE NULL,
  `status` VARCHAR(45) NULL DEFAULT 'Active',
  `Prescription_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Treatment_Prescription1_idx` (`Prescription_id` ASC) VISIBLE,
  CONSTRAINT `fk_Treatment_Prescription1`
    FOREIGN KEY (`Prescription_id`)
    REFERENCES `mydb`.`Prescription` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `department_id` BIGINT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `specialty` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `hired_date` DATE NULL,
  `Treatment_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Doctor_Treatment1_idx` (`Treatment_id` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Treatment1`
    FOREIGN KEY (`Treatment_id`)
    REFERENCES `mydb`.`Treatment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT NOT NULL,
  `room_id` BIGINT NOT NULL,
  `admitted_date` DATE NOT NULL,
  `discharge_date` DATE NULL,
  `admission_type` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'Active',
  `Treatment_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Admission_Treatment1_idx` (`Treatment_id` ASC) VISIBLE,
  CONSTRAINT `fk_Admission_Treatment1`
    FOREIGN KEY (`Treatment_id`)
    REFERENCES `mydb`.`Treatment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `id` BIGINT NOT NULL,
  `department_id` BIGINT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `floort` INT ZEROFILL NULL,
  `capacity` INT NOT NULL AUTO_INCREMENT,
  `room_type` VARCHAR(45) NULL,
  `is_available` TINYINT(1) NULL,
  `Admission_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `department_id_UNIQUE` (`department_id` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_Room_Admission1_idx` (`Admission_id` ASC) VISIBLE,
  CONSTRAINT `fk_Room_Admission1`
    FOREIGN KEY (`Admission_id`)
    REFERENCES `mydb`.`Admission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointment` (
  `id` BIGINT NOT NULL,
  `patient_id` BIGINT NOT NULL,
  `department_id` BIGINT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `purpose` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'Scheduled',
  `bill_amount` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `hospital_id` BIGINT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(45) NULL,
  `head_doctor_id` BIGINT NULL,
  `Doctor_id` BIGINT NOT NULL,
  `Room_id` BIGINT NOT NULL,
  `Appointment_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_Department_Doctor1_idx` (`Doctor_id` ASC) VISIBLE,
  INDEX `fk_Department_Room1_idx` (`Room_id` ASC) VISIBLE,
  INDEX `fk_Department_Appointment1_idx` (`Appointment_id` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Doctor1`
    FOREIGN KEY (`Doctor_id`)
    REFERENCES `mydb`.`Doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Department_Room1`
    FOREIGN KEY (`Room_id`)
    REFERENCES `mydb`.`Room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Department_Appointment1`
    FOREIGN KEY (`Appointment_id`)
    REFERENCES `mydb`.`Appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospital` (
  `ID` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `ID` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `Department_id` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Hospital_Department_idx` (`Department_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_Department`
    FOREIGN KEY (`Department_id`)
    REFERENCES `mydb`.`Department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Insurance` (
  `id` BIGINT NOT NULL,
  `patient_id` BIGINT NOT NULL,
  `insurance_type_id` BIGINT NULL,
  `policy_number` VARCHAR(45) NULL,
  `insured` TINYINT(0) NOT NULL DEFAULT 0,
  `expiry_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `gender` CHAR(1) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `emergency_contact_name` VARCHAR(45) NULL,
  `emergency_contact_phone` VARCHAR(45) NULL,
  `Patient_id` BIGINT NOT NULL,
  `Appointment_id` BIGINT NOT NULL,
  `Insurance_id` BIGINT NOT NULL,
  `Treatment_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Patient_Appointment1_idx` (`Appointment_id` ASC) VISIBLE,
  INDEX `fk_Patient_Insurance1_idx` (`Insurance_id` ASC) VISIBLE,
  INDEX `fk_Patient_Treatment1_idx` (`Treatment_id` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_Patient1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Admission` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patient_Appointment1`
    FOREIGN KEY (`Appointment_id`)
    REFERENCES `mydb`.`Appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patient_Insurance1`
    FOREIGN KEY (`Insurance_id`)
    REFERENCES `mydb`.`Insurance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patient_Treatment1`
    FOREIGN KEY (`Treatment_id`)
    REFERENCES `mydb`.`Treatment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insurance_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Insurance_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `coverage_perentage` DECIMAL(5,2) NULL DEFAULT 0.00,
  `description` TEXT NULL,
  `Insurance_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Insurance_type_Insurance1_idx` (`Insurance_id` ASC) VISIBLE,
  CONSTRAINT `fk_Insurance_type_Insurance1`
    FOREIGN KEY (`Insurance_id`)
    REFERENCES `mydb`.`Insurance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor_appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor_appointment` (
  `Doctor_id` BIGINT NOT NULL,
  `Appointment_id` BIGINT NOT NULL,
  PRIMARY KEY (`Doctor_id`, `Appointment_id`),
  INDEX `fk_Doctor_has_Appointment_Appointment1_idx` (`Appointment_id` ASC) VISIBLE,
  INDEX `fk_Doctor_has_Appointment_Doctor1_idx` (`Doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_has_Appointment_Doctor1`
    FOREIGN KEY (`Doctor_id`)
    REFERENCES `mydb`.`Doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_Appointment_Appointment1`
    FOREIGN KEY (`Appointment_id`)
    REFERENCES `mydb`.`Appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
