-- MySQL Script generated by MySQL Workbench
-- Fri Nov  7 15:47:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`hospitals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospitals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hospital_id` BIGINT UNSIGNED NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_departments_hospital_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_departments_hospital`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mydb`.`hospitals` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctors` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `specialty` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `hired_date` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_doctors_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`departments` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insurance_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`insurance_types` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `coverage_percentage` DECIMAL(5,2) NULL DEFAULT 0.00,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insurances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`insurances` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `insurance_type_id` BIGINT NULL,
  `policy_number` VARCHAR(45) NULL,
  `insured` TINYINT(0) NOT NULL DEFAULT 0,
  `expiry_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_insurances_insurance_type_idx` (`insurance_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_insurances_insurance_type`
    FOREIGN KEY (`insurance_type_id`)
    REFERENCES `mydb`.`insurance_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patients` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `gender` CHAR(1) NULL,
  `phone` VARCHAR(45) NULL,
  `insurance_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_patients_insurance_idx` (`insurance_id` ASC) VISIBLE,
  CONSTRAINT `fk_patients_insurance`
    FOREIGN KEY (`insurance_id`)
    REFERENCES `mydb`.`insurances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rooms` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `floor` INT NULL,
  `capacity` INT NOT NULL,
  `room_type` VARCHAR(45) NULL,
  `is_available` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_rooms_department_number` (`department_id` ASC, `number` ASC) INVISIBLE,
  CONSTRAINT `fk_rooms_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`appointments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `date_time` DATETIME NOT NULL,
  `purpose` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'Scheduled',
  `bill_amount` DECIMAL(10,2) NULL,
  `doctor_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_appointments_patient_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_appointments_doctor_idx` (`doctor_id` ASC) VISIBLE,
  INDEX `fk_appointments_department_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_appointments_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointments_doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointments_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`admissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `room_id` BIGINT UNSIGNED NOT NULL,
  `admitted_date` DATE NOT NULL,
  `discharge_date` DATE NULL,
  `admission_type` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'Active',
  PRIMARY KEY (`id`),
  INDEX `fk_admissions_room_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_admissions_patient_idx` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_admissions_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patients` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_admissions_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`treatments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`treatments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `doctor_id` BIGINT UNSIGNED NOT NULL,
  `diagnosis` VARCHAR(45) NOT NULL,
  `treatment_start_date` DATE NULL,
  `treatment_end_date` DATE NULL,
  `status` VARCHAR(45) NULL DEFAULT 'Active',
  PRIMARY KEY (`id`),
  INDEX `fk_treatments_doctor_idx` (`doctor_id` ASC) VISIBLE,
  INDEX `fk_treatments_patient_idx` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_treatments_doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctors` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_treatments_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patients` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prescriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prescriptions` (
  `id` BIGINT NOT NULL,
  `treatment_id` BIGINT NOT NULL,
  `medication` VARCHAR(45) NULL,
  `dosage_mg` INT NULL,
  `frequency` VARCHAR(45) NULL,
  `duration_days` INT NULL,
  `instructions` TEXT NULL,
  `prescribed_date` DATE NULL DEFAULT CURRENT_DATE,
  PRIMARY KEY (`id`),
  INDEX `fk_prescriptions_treatment_idx` (`treatment_id` ASC) VISIBLE,
  CONSTRAINT `fk_prescriptions_treatment`
    FOREIGN KEY (`treatment_id`)
    REFERENCES `mydb`.`treatments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
